# HTTP Server
server:
  port: ${ADMIN_SERVER_PORT:9999}   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
     preferIpAddress: true
