server:  
  port: 1111   # HTTP port

logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    co.com.ceiba: 'DEBUG'

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false 