#Configuration for failfast=false

# HTTP Server
server:
  port: 3333   # HTTP port
  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    co.com.ceiba: 'DEBUG'

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:1111/eureka/

# Spring properties
spring:
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory      # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path: /templates/error